###############################################################################
# Candidate : Vivek R
# Contact   : vivekravi9496497657@gmail.com | +91 8590609366
# Project   : HabotConnect Hiring Project 1.0
#             Junior Cloud & DevOps Engineer (GCP / Django / React)
# File      : modules/bigquery_staged/main.tf
# Purpose   : The D1 Staged/Enforced dataset - where validated onboarding
#             events become trustworthy analytics input.
#
#             Components:
#               1. Dataset with Customer-Managed Encryption, default table
#                  expiration, and deletion protection.
#               2. student_onboarding_events_enforced - REQUIRED-mode schema,
#                  partitioned by submission date with mandatory partition
#                  filter, clustered by difficulty category. The Pub/Sub
#                  BigQuery subscription enforces this exact schema at write
#                  time, which is what prevents the schema-mismatch incident
#                  described in the hiring scenario from recurring silently.
#               3. rls_principal_clearance - allowlist mapping each analytics
#                  principal to the difficulty categories it may read.
#               4. student_onboarding_events_secure_view - Row-Level Security
#                  surface. Consumers receive SELECT on this view ONLY;
#                  direct access to the base table is never granted, and the
#                  view is an authorized view so it can read the base table
#                  without widening consumer permissions.
#
#             Why an authorized view rather than a native ROW ACCESS POLICY:
#             the Terraform Google provider has no first-class resource for
#             CREATE ROW ACCESS POLICY statements, so encoding that DDL would
#             require a non-declarative provisioner hack. The authorized view
#             achieves identical row filtering with pure declarative
#             resources. docs/assumptions.md records the native-policy
#             equivalent DDL and the migration path once provider support
#             lands. Every filter predicate is deterministic binary logic -
#             the same Poka-Yoke principle applied in Task 3.
###############################################################################

resource "google_bigquery_dataset" "staged" {
  project                     = var.project_id
  dataset_id                  = var.dataset_id
  friendly_name               = "D1 Staged Enforced Staging"
  description                 = "Validated student onboarding events. Schema-enforced writes only; reads flow through the Row-Level Security view."
  location                    = var.region
  default_table_expiration_ms = var.table_expiration_days * 24 * 60 * 60 * 1000

  # Access management stays uniform: no legacy per-view ACLs.
  default_partition_expiration_ms = null

  # Destroying the dataset with contents intact is refused unless an operator
  # explicitly flips delete_contents_on_destroy during a sanctioned teardown.
  # Individual tables additionally carry deletion_protection below.
  delete_contents_on_destroy = false

  default_encryption_configuration {
    kms_key_name = var.kms_key_id
  }

  labels = var.labels
}

resource "google_bigquery_table" "enforced" {
  project             = var.project_id
  dataset_id          = google_bigquery_dataset.staged.dataset_id
  table_id            = "student_onboarding_events_enforced"
  friendly_name       = "Student Onboarding Events Enforced"
  description         = "REQUIRED-mode mirror of the Django REST Framework serializer contract. Written exclusively by the Pub/Sub BigQuery subscription."
  deletion_protection = true

  schema = jsonencode([
    {
      name        = "submission_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Universally unique identifier generated by the onboarding application programming interface."
    },
    {
      name        = "parent_full_name"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Full name of the requesting parent or legal guardian."
    },
    {
      name        = "parent_email"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Contact electronic mail address of the parent or legal guardian."
    },
    {
      name        = "parent_phone"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Contact telephone number of the parent or legal guardian in international format."
    },
    {
      name        = "child_full_name"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Full name of the child requiring Learning Support Assistant matching."
    },
    {
      name        = "child_date_of_birth"
      type        = "DATE"
      mode        = "REQUIRED"
      description = "Date of birth of the child; age eligibility is validated upstream."
    },
    {
      name        = "learning_difficulty_category"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Closed-set category describing the child's primary learning difficulty."
    },
    {
      name        = "support_needs_summary"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Optional free-text context supplied by the parent."
    },
    {
      name        = "parental_consent_granted"
      type        = "BOOLEAN"
      mode        = "REQUIRED"
      description = "Decision Yes/No outcome: parent granted consent to process the onboarding request."
    },
    {
      name        = "data_processing_consent_granted"
      type        = "BOOLEAN"
      mode        = "REQUIRED"
      description = "Decision Yes/No outcome: parent granted consent for data processing under the privacy policy."
    },
    {
      name        = "dcyn_all_rules_passed"
      type        = "BOOLEAN"
      mode        = "REQUIRED"
      description = "Decision Yes/No aggregate: true only when every validation rule returned Yes."
    },
    {
      name        = "dcyn_decision_record"
      type        = "JSON"
      mode        = "NULLABLE"
      description = "Complete per-rule Decision Yes/No evaluation record retained for audit."
    },
    {
      name        = "submitted_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Moment the onboarding form passed validation at the application programming interface."
    }
  ])

  time_partitioning {
    type  = "DAY"
    field = "submitted_at"
  }

  require_partition_filter = true

  clustering = ["learning_difficulty_category"]

  encryption_configuration {
    kms_key_name = var.kms_key_id
  }

  depends_on = [google_bigquery_dataset.staged]
}

resource "google_bigquery_table" "rls_clearance" {
  project             = var.project_id
  dataset_id          = google_bigquery_dataset.staged.dataset_id
  table_id            = "rls_principal_clearance"
  friendly_name       = "Row-Level Security Principal Clearance"
  description         = "Maps each analytics principal to the learning difficulty categories it is cleared to read. Maintained by platform operations."
  deletion_protection = true

  schema = jsonencode([
    {
      name        = "principal_email"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Lowercase electronic mail identity of the querying principal."
    },
    {
      name        = "cleared_category"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Learning difficulty category value the principal may read."
    }
  ])

  encryption_configuration {
    kms_key_name = var.kms_key_id
  }

  depends_on = [google_bigquery_dataset.staged]
}

resource "google_bigquery_table" "secure_view" {
  project       = var.project_id
  dataset_id    = google_bigquery_dataset.staged.dataset_id
  table_id      = "student_onboarding_events_secure_view"
  friendly_name = "Student Onboarding Events Secure View"
  description   = "Only read surface for consumers. Returns rows filtered by the Row-Level Security clearance allowlist."

  view {
    query = <<-SQL
      SELECT
        enforced_table.submission_id,
        enforced_table.parent_full_name,
        enforced_table.parent_phone,
        enforced_table.child_full_name,
        enforced_table.child_date_of_birth,
        enforced_table.learning_difficulty_category,
        enforced_table.parental_consent_granted,
        enforced_table.data_processing_consent_granted,
        enforced_table.dcyn_all_rules_passed,
        enforced_table.submitted_at
      FROM
        `${var.project_id}.${var.dataset_id}.student_onboarding_events_enforced` AS enforced_table
      WHERE
        EXISTS (
          SELECT
            1
          FROM
            `${var.project_id}.${var.dataset_id}.rls_principal_clearance` AS clearance
          WHERE
            LOWER(clearance.principal_email) = SESSION_USER()
            AND clearance.cleared_category = enforced_table.learning_difficulty_category
        )
    SQL

    use_legacy_sql = false
  }

  # Parent contact email is deliberately excluded from the projection:
  # analytics consumers never need the most sensitive direct-contact field.
  encryption_configuration {
    kms_key_name = var.kms_key_id
  }

  deletion_protection = true

  depends_on = [
    google_bigquery_table.enforced,
    google_bigquery_table.rls_clearance,
  ]
}

# Authorize the view so it may read its source tables while consumers of the
# view gain no permissions on those sources.
resource "google_bigquery_dataset_access" "authorized_secure_view" {
  project    = var.project_id
  dataset_id = google_bigquery_dataset.staged.dataset_id

  view {
    project_id = var.project_id
    dataset_id = google_bigquery_dataset.staged.dataset_id
    table_id   = google_bigquery_table.secure_view.table_id
  }

  depends_on = [google_bigquery_table.secure_view]
}
