# Candidate : Vivek R
# Contact   : vivekravi9496497657@gmail.com | +91 8590609366
# Generated by: python manage.py makemigrations onboarding
# Generated by Django 5.1.4 on 2026-08-24 12:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentOnboardingSubmission",
            fields=[
                (
                    "submission_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parent_full_name", models.CharField(max_length=120)),
                ("parent_email", models.EmailField(max_length=254)),
                ("parent_phone", models.CharField(max_length=16)),
                ("child_full_name", models.CharField(max_length=120)),
                ("child_date_of_birth", models.DateField()),
                ("learning_difficulty_category", models.CharField(max_length=64)),
                ("support_needs_summary", models.TextField(blank=True, default="")),
                ("parental_consent_granted", models.BooleanField()),
                ("data_processing_consent_granted", models.BooleanField()),
                (
                    "dcyn_all_rules_passed",
                    models.BooleanField(default=True, editable=False),
                ),
                ("dcyn_decision_record", models.JSONField(editable=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Student Onboarding Submission",
                "verbose_name_plural": "Student Onboarding Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
